version: 2
jobs:
  build:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - checkout
      - run: echo "A first hello"

database:
  override:
    - bundle exec rake db:create db:schema:load db:seed --trace

deployment:
 production:
    branch: master
    commands:
      - git fetch origin --unshallow
      - git push git@heroku.com:tech-blog.git $CIRCLE_SHA1:master
      - heroku run rake db:migrate --app tech-blog
      - heroku restart --app tech-blog
